# Generated by Django 4.2.4 on 2023-08-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loan_approved_at_loan_denied_at_loan_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='frequency',
            field=models.CharField(default='weekly'),
        ),
    ]
