# Generated by Django 4.2.4 on 2023-08-28 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_loan_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
